;;; -*- lexical-binding: t -*-
(require 'reftex-xref)
(require 'f)
(require 's)
;;; Code:

(defun reftex-xref-output-rule-test-failures (failures)
  (--each failures (princ (format "\t%s\n" it))))

(setq test-data-dir (f-expand "./test/data"))
(setq test-data-dir-singlefile (f-join test-data-dir "singlefile"))
(setq test-data-dir-multifiles (f-join test-data-dir "multifiles"))

;; * tests existence directory

(ert-deftest reftex-xref-test001-data-dir-exists-test ()
  (should (f-dir? test-data-dir)))

(ert-deftest reftex-xref-test002-data-dir-multifiles-exists-test ()
  (should (f-dir? test-data-dir-multifiles)))

(ert-deftest reftex-xref-test003-data-dir-singlefile-exists-test ()
  (should (f-dir? test-data-dir-singlefile)))

;; * tests from ref to label (find-definition)
;; ** one single LaTeX file (sf)
(ert-deftest reftex-xref-test004-sf-from-eqref-to-label-after ()
  (let ((tex-file (f-join test-data-dir-singlefile "main.tex")))
    (with-current-buffer (find-file-noselect tex-file t)
      (LaTeX-mode)
      (setq TeX-master "main")
      (reftex-parse-all)
      (goto-char (point-min))
      (forward-line 15)
      (forward-char 43)
      (reftex-xref-activate)
      (xref-find-definitions (xref-backend-identifier-at-point 'reftex))
      (should (= (point) 1066)))))

(ert-deftest reftex-xref-test005-sf-from-eqref-to-label-before ()
  (let ((tex-file (f-join test-data-dir-singlefile "main.tex")))
    (with-current-buffer (find-file-noselect tex-file t)
      (LaTeX-mode)
      (setq TeX-master "main")
      (reftex-parse-all)
      (goto-char (point-min))
      (forward-line 30)
      (forward-char 60)
      (reftex-xref-activate)
      (xref-find-definitions (xref-backend-identifier-at-point 'reftex))
      (should (= (point) 1047)))))

(ert-deftest reftex-xref-test006-sf-from-ref-to-label-after ()
  (let ((tex-file (f-join test-data-dir-singlefile "main.tex")))
    (with-current-buffer (find-file-noselect tex-file t)
      (LaTeX-mode)
      (setq TeX-master "main")
      (reftex-parse-all)
      (goto-char (point-min))
      (forward-line 54)
      (forward-char 67)
      (reftex-xref-activate)
      (xref-find-definitions (xref-backend-identifier-at-point 'reftex))
      (should (= (point) 2720)))))

(ert-deftest reftex-xref-test007-sf-from-ref-to-label-before ()
  (let ((tex-file (f-join test-data-dir-singlefile "main.tex")))
    (with-current-buffer (find-file-noselect tex-file t)
      (LaTeX-mode)
      (setq TeX-master "main")
      (reftex-parse-all)
      (goto-char (point-min))
      (forward-line 46)
      (forward-char 66)
      (reftex-xref-activate)
      (xref-find-definitions (xref-backend-identifier-at-point 'reftex))
      (should (= (point) 102)))))

;; ** with include (multifiles parsing)
(ert-deftest reftex-xref-test008-mf-from-eqref-to-label-after ()
  (let ((tex-file (f-join test-data-dir-multifiles "first.tex")))
    (with-current-buffer (find-file-noselect tex-file t)
      (LaTeX-mode)
      (setq TeX-master "main")
      (reftex-parse-all)
      (goto-char (point-min))
      (forward-line 10)
      (forward-char 43)
      (reftex-xref-activate)
      (xref-find-definitions (xref-backend-identifier-at-point 'reftex))
      (should (= (point) 1033)))))

(ert-deftest reftex-xref-test009-mf-from-eqref-to-label-before ()
  (let ((tex-file (f-join test-data-dir-multifiles "first.tex")))
    (with-current-buffer (find-file-noselect tex-file t)
      (LaTeX-mode)
      (setq TeX-master "main")
      (reftex-parse-all)
      (goto-char (point-min))
      (forward-line 25)
      (forward-char 60)
      (reftex-xref-activate)
      (xref-find-definitions (xref-backend-identifier-at-point 'reftex))
      (should (= (point) 1014)))))

(ert-deftest reftex-xref-test010-mf-from-ref-to-label-after ()
  (let ((tex-file (f-join test-data-dir-multifiles "first.tex")))
    (with-current-buffer (find-file-noselect tex-file t)
      (LaTeX-mode)
      (setq TeX-master "main")
      (reftex-parse-all)
      (goto-char (point-min))
      (forward-line 26)
      (forward-char 17)
      (reftex-xref-activate)
      (xref-find-definitions (xref-backend-identifier-at-point 'reftex))
      (should (= (point) 1665)))))

(ert-deftest reftex-xref-test011-mf-from-ref-to-label-before ()
  (let ((tex-file (f-join test-data-dir-multifiles "first.tex")))
    (with-current-buffer (find-file-noselect tex-file t)
      (LaTeX-mode)
      (setq TeX-master "main")
      (reftex-parse-all)
      (goto-char (point-min))
      (forward-line 41)
      (forward-char 66)
      (reftex-xref-activate)
      (xref-find-definitions (xref-backend-identifier-at-point 'reftex))
      (should (= (point) 38)))))

(ert-deftest reftex-xref-test012-mf-from-ref-to-label-otherfile ()
  (let ((tex-file (f-join test-data-dir-multifiles "first.tex")))
    (with-current-buffer (find-file-noselect tex-file t)
      (LaTeX-mode)
      (setq TeX-master "main")
      (reftex-parse-all)
      (goto-char (point-min))
      (forward-line 8)
      (forward-char 58)
      (reftex-xref-activate)
      (xref-find-definitions (xref-backend-identifier-at-point 'reftex))
      (should (and (= (point) 2028)
                   (string= "second.tex" (buffer-name)))))
    (kill-buffer "second.tex")))
